services:
  db:
    image: postgres:16-alpine
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: messenger_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: messenger_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/wsnox.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build: .
    container_name: messenger_backend
    restart: always
    env_file: .env
    environment:
      - DEBUG=true
      - DOCKER_MODE=true
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - db
      - redis
    volumes:
      - ./src/messenger/backend:/app/src/messenger/backend
      - ./alembic:/alembic
      - ./alembic.ini:/alembic.ini


volumes:
  db_data:
  redis_data:
