name: Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/benzin8/wsnox:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER.SERVER_HOST }}
          username: ${{ secrets.SERVER.SERVER_USER }}
          key: ${{ secrets.SERVER.SERVER_SSH_KEY }}
          script: |
            {
            echo "DB_USER=${{ secrets.DB.DB_USER }}"
            echo "DB_PASS=${{ secrets.DB.DB_PASS }}"
            echo "DB_HOST=${{ secrets.DB.DB_HOST }}"
            echo "DB_PORT=${{ secrets.DB.DB_PORT }}"
            echo "DB_NAME=${{ secrets.DB.DB_NAME }}"
            echo "SMTP_HOST=${{ secrets.SMTP.SMTP_HOST }}"
            echo "SMTP_PORT=${{ secrets.SMTP.SMTP_PORT }}"
            echo "SMTP_USER=${{ secrets.SMTP.SMTP_USER }}"
            echo "SMTP_PASSWORD=${{ secrets.SMTP.SMTP_PASSWORD }}"
            echo "SECRET_KEY=${{ secrets.SECURITY.SECRET_KEY }}"
            echo "ALGORITHM=${{ secrets.SECURITY.ALGORITHM }}"
            echo "REDIS_URL=${{ secrets.SECURITY.REDIS_URL }}"
            } > ~/WSNox/.env
            cd ~/WSNox
            docker compose pull
            docker compose up -d
